### PR TITLE
Enumerable Any method support

### PR DESCRIPTION
**Pull request by AlexzundeR**
Realize field call hierarchy criteria and on its base create Enumerable Any visitor. 
Add more flexible method of concatenatig fields in base IElasticMapping interface.

### CODE REVIEW

**Comment by damieng** [comment]
Will try and check this out in the next day or two. Why is FieldCallCriteria required rather than just returning a normal terms query? The existing field mapping code should be capable of generating a sub-property name with appropriate .'s in them - we use the path for ContainsAll.

**Comment by AlexzundeR** [comment]
Problem is in impossibility to create Expression that can be mapped to needed structure cause first property is Collection of objects and second property is property of collected object's type. 
Terms criteria and MapField method base on MemberInfo or MemberExpression types, which go from .net core and not support type hacks.

**Comment by AlexzundeR** [comment]
Hello, @damieng! Do you have any new ideas on this request?

**Comment by AlexzundeR** [comment]
Any news, @damieng ? =)

**Comment by damieng** [comment]
Hi Alex.  Will try and take a look again this week.

**Comment by AlexzundeR** [comment]
@damieng, hello!  Have you already take a look?)

**Comment by damieng** [comment]
Hi, started going through this last night but finding it difficult to follow. Can you show what the LINQ query would look like and what ES query it would generate?

**Comment by AlexzundeR** [comment]
I mean queries like something that:`entities.Where(e=>e.CollectionProperty.Any(p=>p.Name=="123"))`. It should be translated to ES query:

<pre><code>{
    "query" : {
        "filtered" : {
            "filter" : {
                "term" : {
                    "collectionProperty.name" : "123"
                }
            }
        }
    }
}</code></pre>

**Comment by jamesjhhan** [comment]
I am in need of this as well.  However, AlexzundeR, I don't think that will work.  
You will need to generate a nested filter.  so instead of just
                "term" : {
                    "collectionProperty.name" : "123"
                }
you need..
                "nested" : {
                    "filter": {
                        "bool": {
                            "must": [
                                {  
                                    "term": {
                                        "collectionProperty.name": "123"
                                    }
                                }
                            ]
                        }
                    },
                    "path": "collectionProperty"

So the entire query should look like this..

{
    "query": {  
        "filtered": {
            "filter" : {
                "nested" : {
                    "filter": {
                        "bool": {
                            "must": [
                                {  
                                    "term": {
                                        "collectionProperty.name": "123"
                                    }
                                }
                            ]
                        }
                    },
                    "path": "collectionProperty"
                }
            }
        }
    },
    "size": 10,
    "timeout": "10s"
}

Here is the reference..
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-nested-filter.html
Please note they have since replaced nested filters with nested queries in 2.0.

**Comment by jamesjhhan** [comment]
Actually you don't need the bool/must enclosure so something like this will work as well..

REPLACE THIS..

"term" : { "collectionProperty.name" : "123" }

WITH..

"nested" : {
    "filter": { "term": { "collectionProperty.name": "123" } },
    "path": "collectionProperty"
}

**Comment by AlexzundeR** [comment]
@jamesjhhan in my case, where i have a collection of any structure, i don't need nested classes. As can you see, in my linq query i select entities where any of stored in collection objects have property that equals value. Yes, this is a very local use case, but in my project very frequent.
P.S. you can try my PR, it works! =)

**Comment by AlexzundeR** [comment]
@jamesjhhan in my case, where i have a collection of any structure, i don't need nested classes. As can you see, in my linq query i select entities where any of stored in collection objects have property that equals value. Yes, this is a very local use case, but in my project very frequent.
P.S. you can try my PR, it works! =)

**Pull request closed without merging**
